# Generated by Django 6.0.4 on 2026-05-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=0, max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('unit_cost', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.categories')),
            ],
        ),
        migrations.CreateModel(
            name='CreditScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('amount_paid', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('nin_number', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.categories')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.products')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total_amount', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount_paid', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('receipt', models.CharField(max_length=100)),
                ('receipt_number', models.IntegerField(unique=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.categories')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.products')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('supplier', models.CharField(max_length=50)),
                ('payment_status', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.categories')),
                ('product_name', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='nyondo_app.products')),
            ],
        ),
    ]
