# Generated by Django 6.0.4 on 2026-05-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
