# Generated by Django 6.0.4 on 2026-05-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
