# Generated by Django 6.0.4 on 2026-05-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0002_alter_products_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
