# Generated by Django 6.0.4 on 2026-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0002_remove_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='transport_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='transport_needed',
            field=models.BooleanField(default=False),
        ),
    ]
