# Generated by Django 6.0.4 on 2026-05-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyondo_app', '0003_alter_products_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
    ]
